variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages/
  MicroBuild_DoNotStrongNameSign: true
  codecov_token: c8862aaf-0c6d-48ee-a4a7-e88af58ef469 # Get a new one from https://codecov.io/
